sudo: false
os:
  - linux
  - osx

cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano

matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      - build-essential
      - gcc
      - python3-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - libblas-dev
      - libhdf5-serial-dev
      - gfortran
      - nvidia-cuda-toolkit
      - cuda

virtualenv:
  system_site_packages: false

language: python
python:
  - "3.5.0"

# command to install dependencies
install:
  # enforce virtualenv
  #- virtualenv -p python3 venv
  #- source venv/bin/activate
  # ensure that Cython get installed first
  - pip install Cython
  - travis_wait travis_retry pip install -r requirements.txt
  # install package
  - pip install -e .

#sudo apt-get install libhdf5-dev;
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
       brew update;
       brew install python3;
       brew install gfortran;
       brew tap homebrew/science;
       brew install openblas;
       brew install hdf5;
    fi

# command to run tests
script: nosetests

notifications:
  on_success: change
  on_failure: change
  recipients:
    - hahnpowell@email.arizona.edu
